name: dockerhub-mirror

on:
  push:
    branches:
      - "client-v4-beta"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Mirror composer image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/composer
          VERSION=2
          PULL_IMAGE=composer:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"

      - name: Mirror custom php74 image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/php
          VERSION=7.4-cli-alpine
          PULL_IMAGE=php:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"
